server:
  port: 9000
  servlet:
    session:
      timeout: 60m

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ENC(g9LpM3RdzrmOPlwsTlPhVw==)


logging:
  level:
    org:
      hibernate: info


auth-service:
  base-url: "http://localhost:8080/api/auth"
  client-id: "client-id"
  secret-id: "secret-id"
