server:
  port: 9000
  servlet:
    session:
      timeout: 60m

spring:
  h2:
    console:
      enabled: true # /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  groovy:
    template:
      allow-session-override:

auth-service:
  base-url: "http://localhost:8080/api/auth"
  client-id: "client-id"
  secret-id: "secret-id"


